### ISSUE TITLE
i_user_filterのForkをChromeウェブストアで配信しても良いですか？

### ISSUE THREAD

**Issue by mmduser1** [mofurion/i_user_filter#1]
素晴しい拡張機能ですが、インストール方法に難があるのを解決したいと思っています

**Comment by mmduser1** [comment]
断念します
失礼いたしました

**Comment by mofurion** [comment]
すみません今気付きました！
MITライセンスなのでもちろん構いません、むしろChromeの勝手にインストールできない問題が解決できなかったので大歓迎です！

**Comment by mmduser1** [comment]
@mofurion 
生きていらしたとは、嬉しい驚きです

自分でもユーザーNG機能の拡張を作ってみたんですが、要素を消した分だけ詰める実装が面倒だったので画像への置き換えでお茶を濁していました

こちらのforkを使えると非常に助かります
ご許可ありがとうございます

**Comment by mmduser1** [comment]
無事審査を通過して公開されました

- chrome
https://chrome.google.com/webstore/detail/iwara-user-filter/amcbakbciimbegoailafbihegadjaocb

- firefox
https://addons.mozilla.org/ja/firefox/addon/iwara-user-filter/

**Comment by mofurion** [comment]
あざす！！！
